name: Tests CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          path: main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci
        working-directory: ./main

      - name: Lint
        run: npm run lint
        working-directory: ./main

      - name: Danger
        run: npx danger ci --dangerfile ./dangerfile.ts
        working-directory: ./main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: npm run test
        working-directory: ./main

      - name: Build
        run: npm run build
        working-directory: ./main

      - name: Publish Dry Run
        run: npm publish --dry-run
        working-directory: ./main/dist

      - name: Pack up for testing project import
        run: |
          npm pack
          mv dsnp-activity-content-*.tgz ../dsnp-activity-content.tgz
        working-directory: ./main/dist

      #     This needs to happen in a non-subfolder of the sdk to prevent resolving from a parent dir node_modules
      - name: Test Project Import
        run: |
          cp -r ./main/src/test/importTest ./
          cd importTest
          npm i ../main/dsnp-activity-content.tgz
          npm test
